# Generated by Django 2.2.5 on 2020-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200929_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agora_welcome_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
