# Generated by Django 2.2.5 on 2020-09-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200930_0947'),
        ('users', '0005_user_agora_welcome_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_question_asked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_question_asked_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('qa', 'QA'), ('design', 'Design'), ('strategy', 'Strategy')], max_length=255),
        ),
    ]
