# Generated by Django 2.2.5 on 2020-09-30 09:41

from django.db import migrations

QUESTIONS_DB = {
    "work_experience": [
        "Tell us about your very first job.",
        "What is the most amusing thing you can remember at your workplace?",
        "What are your special skills you would like to apply at the workplace?",
        "What do you like most about your job?",
        "Describe your team in one word.",
        "What is the weirdest thing you've ever seen in your workspace?",
        "Which of your skills do you feel are being underutilized at work?",
        "Which skills would you like to acquire your ideal workflow?",
        "Tell us about something you used to believe earlier in your career, but you now think about differently.",
        "What is the best career advice you've ever received?",
        "If you could give some advice to beginners in your work area, what would it be?",
        "Tell us about the last time you got angry with a co-worker. What was the cause?",
        "Where do you want to see yourself in 10 years?",
        "In one word, what is the greatest challenge you have faced this month?",
        "Who would you be in a parallel universe?",
    ],
    "lifestyle": [
        "In three words, how would your family and friends describe you?",
        "What's your most favorite place to travel to, and why?",
        "What's your life's biggest dream?",
        "Tell us when last you took a big risk?",
        "What are your top 3 most hated foods?",
        "Do you have any hidden talent? It could be positive or negative.",
        "What is the hidden meaning behind your name? Why were you given the name?",
        "Which best describes you? An introvert or an extrovert?",
        "Tell us 3 random facts about yourself!",
        "Pick something from your pocket/purse and tell us why that thing is inside there.",
        "What is your best season of the year? Why?",
        "What is your best breakfast at home?",
        "Tell us five things you always carry in your backpack!",
        "Name the most intelligent person you know.",
        "Your favorite film genre is what?",
        "Mention somebody you truly admire.",
        "Mountain or beach, which one would you prefer for vacation?",
        "What's your favorite way to spend a rainy weekend at home by yourself?",
        "What's the most unusual food you've ever eaten?",
        "What's the worst dish you have ever made?",
        "What's the most difficult thing you've ever done?",
        "Mention a gift someone gave you that you can never forget?",
        "Mention one thing you love about yourself.",
        "Tell us the bravest thing you've done in your life?",
        "Do you have any tattoo on your body and how does it look like?",
        "How and where did you first meet your best friend?",
        "What's the most amazing thing you've seen in nature?",
        "What piece of clothing best describes you? Why?",
        "What's the oldest item in your wardrobe? How old is it?",
        "Tell us your guilty pleasure!",
        "Any brothers, sisters or cousins? Which one do you have?",
        "Where do you prefer to live - city or countryside?",
        "Have you ever stayed in a countryside for weeks or a year or two?",
        "Do you / Did you ever live outside the city? Where?",
        "How do you relieve stress and anxiety?",
        "What's your weirdest dream ever?",
        "What are you doing next weekend?",
        "Are you a planner or spontaneous?",
        "Has anyone saved your life before? Have you ever saved someone else's?",
    ],
    "what_if": [
        "What strange room/feature would you build in to your dream house?",
        "How would you spend your money if you won the lottery?",
        "If you had to be stuck at a particular age, what would that age be? Why?",
        "If people are to make a film about you, what would the genre be? A science fiction, romantic comedy, action movie or comedy?",
        "What animal would you be, and why?",
        "What would you do if you were invisible for 24 hours?",
        "If you could have any superpower, what would you choose and why?",
        "If your house was on fire and you could only grab three things, what would they be?",
        "What would you be found doing if the police unexpectedly breaks into your home in the day?",
        "If you could travel to anywhere in the galaxy (outside Earth), where would you go, and why?",
        "If you could see in the future, which period would you choose, and why?",
        "If you could only meet one person from history, who would it be?.",
        "If you had one opportunity to run a restaurant, what would you serve?",
    ],
    "hobbies": [
        "What's your favorite music band a decade ago? What of now?",
        "Have you ever met someone famous in person?",
        "If you can choose a famous person to hang out with, who would it be?",
        "What book are you currently reading?",
        "If you could master any skill instantly, what would it be?",
        "What's your best sport or fitness activity?",
        "What animal is your favorite pet? And do you have any pets?",
        "What is your all time favourite movie(s)? List away!",
        "If you are to learn any new skill that is not related to work, what would it be?",
        "What are your all time favorite TV series or shows?",
        "Do you have collections of things (Do we want to know what it is)?",
        "What is your preferred YouTube vlog channels?",
        "You best time of the day is what? Morning, afternoon, evening or night?",
        "What is that thing you have never done before which you want to do next year?",
        "Tell us your best section in a library or bookstore.",
        "What is your preferred music genre?",
        "Have you seen your favorite musician in person?",
        "What is your favorite summer activity?",
        "Tell us a book or movie or video you've read or seen lately and which you would recommend? Why?",
        "What was the worst travel experience of your life?",
        "Do you play any musical instrument, and which?",
        "Do you watch Netflix shows? What's your best?",
    ],
    "childhood": [
        "What is your most memorable childhood story?",
        "What was your best cartoon as a child?",
        "Tell us what's your hero as a child. Why was he/she your hero?",
        "What was your greatest childhood gift?",
        "What's your best memory from childhood, and why?",
        "Have you ever won a medal or trophy?",
        "Mention some embarrassing memories from childhood.",
        "When you were a kid, what did you want to be when you grew up?",
        "How and where did you first meet your best friend?",
        "What were your favorite childhood TV shows and cartoons?",
        "What was your favorite childhood video game you played?",
        "What was your favorite book as a kid?",
        "What was your favorite film you watched as a child?",
        "Where did you spend your summer holidays growing up?",
    ]
}


def create_questions(apps, scheme):
    Question = apps.get_model("questions", "Question")

    for category, questions in QUESTIONS_DB.items():
        for body in questions:
            Question.objects.get_or_create(category=category, body=body)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_questions, lambda x,y: x)
    ]
