# Generated by Django 2.2.5 on 2019-09-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('update', 'update'), ('inform', 'inform')], max_length=255, null=True),
        ),
    ]
