# Generated by Django 2.2.5 on 2019-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190927_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('update', 'update'), ('inform', 'inform')], default='inform', max_length=255, null=True),
        ),
    ]
