# Generated by Django 2.2.5 on 2020-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_create_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('childhood', 'Childhood'), ('what_if', 'What if...'), ('lifestyle', 'Lifestyle'), ('work_experience', 'Work Experience'), ('hobbies', 'Hobbies')], max_length=255),
        ),
    ]
