# Generated by Django 2.2.5 on 2020-09-30 10:59

from django.db import migrations

PROJECTS = [
    "Admin",
    "Ahvo",
    "Algida",
    "Algorand",
    "Alive & Awake",
    "Android",
    "Aventri",
    "Avocare",
    "Backend",
    "Bauer",
    "Blockstack",
    "blogTO",
    "Coinlist",
    "Constellation",
    "Famelog",
    "Fieldguide",
    "Filament",
    "Frontend",
    "FrontRole",
    "Hipo",
    "Hipotalks",
    "iOS",
    "Lexicon",
    "Mastermind",
    "Midas",
    "Moku",
    "Moment",
    "Paird",
    "Pascal",
    "QA",
    "Qube",
    "Rosh Review",
    "Rosh-Review",
    "Tryouts",
    "Vesta",
    "Wanderwell",
    "Wolarf",
]


def create_projects(apps, schema):
    Project = apps.get_model("projects", "Project")

    for project_name in PROJECTS:
        Project.objects.create(name=project_name)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_projects, lambda x, y: x)
    ]
