version: '3'

services:

  nginx:
    image: nginx:1.15.7
    depends_on:
      - app
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app:app-async  # We only run a single server in development
    volumes:
      - ./conf/nginx_development.conf:/etc/nginx/conf.d/default.conf

  app:
    environment:
      - DJANGO_SETTINGS_MODULE=team_directory.settings
      - PYTHONBREAKPOINT=ipdb.set_trace
    tty: true
    ports:
      # For debugging
      - 4000:4000

  postgres:
    environment:
      - POSTGRES_PASSWORD=test

  celery:
    environment:
      - C_FORCE_ROOT=1
      - DJANGO_SETTINGS_MODULE=team_directory.settings

  celerybeat:
    environment:
      - C_FORCE_ROOT=1
      - DJANGO_SETTINGS_MODULE=team_directory.settings

  flower:
    environment:
      - DJANGO_SETTINGS_MODULE=team_directory.settings
    ports:
      - 5555:5555













